version: '3'
# Replace network name with the fabric test-network name 
services:
  redis: 
    image: 'redis'
    command: ['--maxmemory-policy','noeviction','--requirepass','${REDIS_PASSWORD}']
    ports:
      - 6379:6379
    networks:
      - fabric_test
  
  nodeapp:
    image: 'rest-api'
    command: ['start:dotenv']
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      - REDIS_PASSWORD
    networks:
        - fabric_test


networks:
  fabric_test:
    external: true 
